# Generated by Django 4.2.7 on 2026-04-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_governmentscheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentscheme',
            name='pdf_document',
            field=models.FileField(blank=True, help_text='Upload a PDF. Its text will be automatically extracted into the details box upon saving.', null=True, upload_to='schemes/pdfs/'),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='details',
            field=models.TextField(blank=True, help_text='Provide extra info, eligibility, benefits, and how to apply. You can use markdown or plain text.'),
        ),
    ]
