# Generated by Django 4.2.7 on 2026-07-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_governmentscheme_pdf_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
