# Generated by Django 4.2.7 on 2026-08-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentscheme',
            name='application_deadline',
            field=models.CharField(blank=True, default='Ongoing / Open', help_text='e.g. 31 August 2026, 31 October 2026, or Ongoing', max_length=255),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the application portal currently open/active?'),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='last_updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
