# Generated by Django 4.2.7 on 2026-08-02 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0007_governmentscheme_application_deadline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigiLockerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_linked', models.BooleanField(default=False)),
                ('digilocker_id', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('masked_aadhaar', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(default=28)),
                ('gender', models.CharField(default='Male', max_length=20)),
                ('state', models.CharField(default='Karnataka', max_length=100)),
                ('annual_income_lakhs', models.FloatField(default=1.5)),
                ('category', models.CharField(default='OBC', max_length=50)),
                ('occupation', models.CharField(default='Farmer / Student', max_length=100)),
                ('ration_card_no', models.CharField(blank=True, max_length=50, null=True)),
                ('verified_documents', models.JSONField(blank=True, default=list)),
                ('linked_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digilocker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
