# Generated by Django 4.2.7 on 2026-08-02 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_digilockerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DigiLockerProfile',
        ),
    ]
